[build]
  command = "npm install --prefix netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "https://uxmikko.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
